# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: githug-pr-merge
app: githug-pr-merge
org: vsamotaev

plugins:
  - serverless-python-requirements
custom:
  app_acronym: githug-pr-merge
  default_stage: dev
  local_debug: False
  stage: ${opt:stage, self:custom.default_stage}
  stack_name: ${self:custom.app_acronym}-${self:custom.stage}
  region: ${opt:region, self:provider.region}
  deletion_policy: Delete
  url_default_ttl: 60

provider:
  name: aws
  runtime: python3.8
  stage: ${opt:stage, 'dev'} # Set the default stage used. Default is dev
  region: eu-central-1
  memorySize: 128 # Overwrite the default memory size. Default is 1024
  environment:
    TRIGGER_BRANCHES: master,stage
    REGION: ${self:custom.region}
    URL_DEFAULT_TTL: ${self:custom.url_default_ttl}
    LOCAL_DEBUG: ${self:custom.local_debug}
    JENKINS_USER: pedrodparkes
    JENKINS_USER_TOKEN: 420time
    JENKINS_URL: https://jenkins.example.com
    JENKINS_PIPELINE_NAME: example-pipeline

package:
  exclude:
    - .requirements/**
    - env/**
    - package.json
    - package-lock.json
    - README.md
    - requirements.txt
    - .python-version
    - curl.sh

functions:
  trigger:
    name: ${self:custom.stack_name}-trigger
    description: Trigger Jenkins build by merging GitHub PR to master
    handler: asset/trigger.trigger
    memorySize: 128
    timeout: 10
    events:
      - http:
          path: trigger
          method: post
